name: market
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  get:
#  jiffy:
#  intel:
  http:
#  cached_network_images:
#  image_picker:
#  show_up_animation:
#  auto_animated:
  #Google Map
#  flutter_polyline_points:
#  google_maps_flutter:
#  geolocator:
#  geocoding:
  #Firebase And Notification
  firebase_messaging:
  firebase_core:
#  flutter_local_notifications:
  cloud_firestore:
# # Local Data Cache
  sqflite:
  shared_preferences:
##  path:
##  #Qrcode
##  qr_flutter:
##  scan:
##  grouped_list:
##  url_launcher:
##  dropdown_search:
##  badges:
  font_awesome_flutter:
  google_sign_in:
#  device_preview:
  awesome_dialog:
  responsive_builder:
  flutter_otp_text_field: ^1.2.0
  dartz: ^0.10.1
  lottie: ^3.1.2
#  image_pickers:
#



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  assets:
    - assets/logo/
    - assets/lottie/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf
        - asset: assets/fonts/Cairo/Cairo-Medium.ttf
          weight: 700

    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-Regular.ttf
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-Bold.ttf
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-Medium.ttf
          weight: 700

